language: node_js

node_js:
- 6
- 8
- 10

branches:
  only:
  - master

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install yarn
  - npm install cnpm -g --registry=https://registry.npm.taobao.org

install:
  - npm install

script:
  - npm test
