language: node_js

node_js:
- 6
- 8
- 10

branches:
  only:
  - master

before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - npm install cnpm -g --registry=https://registry.npm.taobao.org

install:
  - npm install

script:
  - npm test
